name: Update checks

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1

jobs:
  main:
    runs-on: ubuntu-latest
    name: Update checks
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: prepare pip
        run:
          python -m pip install --upgrade pip wheel
      - name: install Python deps
        run:
          python -m pip install --upgrade beautifulsoup4 lxml pyyaml requests
      - name: check for updates
        run:
          python check_for_new_package_versions.py
